import { Analytics } from '@vercel/analytics/next';
import type { Metadata } from "next";
import { Martian_Mono } from "next/font/google";
import { Toaster } from 'react-hot-toast';
import "./globals.css";
import 'react-tooltip/dist/react-tooltip.css'

const martianMono = Martian_Mono({
  variable: "--font-martian-mono",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${martianMono.className}  antialiased bg-white`}
      >
        {children}
        <Toaster position="bottom-center" />
        <Analytics />
      </body>
    </html>
  );
}
